[package]
name = "vpnr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libp2p = { version = ">=0.55.0", features = [
    "tokio",
    "gossipsub",
    "mdns",
    "noise",
    "macros",
    "tcp",
    "tls",
    "yamux",
    "quic",
    "ping",
    "identify",
    "relay",
    "upnp",
    "rendezvous",
    "pnet",
    "relay",
    "kad",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
futures = { version = ">=0.3" }
tokio = { version = "1.44", features = ["full"] }
pnet = "0.35.0"
tun = { version = "0.7.17", features = ["async"] }
