services:
    vpnr_1:
        image: chipfunk/vpnr:latest
        command:
            - start
        environment:
            - VPNR_IP_ADDRESS=172.28.5.1
            - VPNR_PRIVATE_KEYFILE_PATH=/run/secrets/vpnr_1
            - VPNR_LISTEN_ADDR=0.0.0.0
            - VPNR_LISTEN_PORT=4001
        secrets:
            - vpnr_1
        volumes:
            - vpnr_1:/data
        networks:
            - nodes

    vpnr_2:
        image: chipfunk/vpnr:latest
        command:
            - start
        environment:
            - VPNR_IP_ADDRESS=172.28.5.2
            - VPNR_PRIVATE_KEYFILE_PATH=/run/secrets/vpnr_2
            - VPNR_LISTEN_ADDR=0.0.0.0
            - VPNR_LISTEN_PORT=4002
        secrets:
            - vpnr_2
        volumes:
            - vpnr_2:/data
        networks:
            - nodes

secrets:
    vpnr_1:
        file: ./private-key-1.ed25519
    vpnr_2:
        file: ./private-key-2.ed25519

volumes:
    vpnr_1: {}
    vpnr_2: {}

networks:
    nodes:
        driver: bridge
        internal: true
        enable_ipv4: true
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
