services:
    vpnr_1:
        build: .
        command: start
        environment:
            - VPNR_IP_ADDRESS=172.28.5.1
            - VPNR_PRIVATE_KEYFILE_PATH=/run/secrets/private-key-1
            - VPNR_LISTEN_ADDR=0.0.0.0
            - VPNR_LISTEN_PORT=4001
        volumes:
            - shared_storage:/data
        networks:
            - nodes

    vpnr_2:
        build: .
        command: start
        environment:
            - VPNR_IP_ADDRESS=172.28.5.2
            - VPNR_PRIVATE_KEYFILE_PATH=/run/secrets/private-key-2
            - VPNR_LISTEN_ADDR=0.0.0.0
            - VPNR_LISTEN_PORT=4002
        volumes:
            - shared_storage:/data
        networks:
            - nodes

volumes:
    shared_storage: {}

networks:
    nodes:
        driver: bridge
        internal: true
        enable_ipv4: true
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
